Models/DashboardViewModel.cs
namespace süleyman.Models
{
    public class DashboardViewModel
    {
    }
}

Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

public class AboutController : Controller
{
    public IActionResult Index()
    {
        return View(); // Bu, "Views/About/Index.cshtml" dosyasını kullanır.
    }
}

Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;


namespace süleyman.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Default/Index.cshtml
@{
    Layout = null;
}

<h3>
    <!DOCTYPE html>
   
    <html class="no-js" lang="en">
     
    <body id="top">

        @await Component.InvokeAsync("_HeadComponentPartial")
       
        @await Component.InvokeAsync("_FeatureComponentPartial")
                                           
        @await Component.InvokeAsync("_PortfolioComponentPartial")     

        @await Component.InvokeAsync("_ContactComponentPartial")
              
        @await Component.InvokeAsync("_FooterComponentPartial")
    </body>

</html>
</h3>  

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Ana Sayfa";
    Layout = "~/Views/Shared/_Layout.cshtml"; 
}
<!-- Bileşenleri çağırma -->
@await Html.PartialAsync("~/Views/Shared/Components/_NavbarComponentPartial/Default.cshtml")
@await Html.PartialAsync("~/Views/Shared/Components/_HeadComponentPartial/Default.cshtml")
@await Html.PartialAsync("~/Views/Shared/Components/_FeatureComponentPartial/Default.cshtml")
@await Html.PartialAsync("~/Views/Shared/Components/_AboutComponentPartial/Default.cshtml")
@await Html.PartialAsync("~/Views/Shared/Components/_PortfolioComponentPartial/Default.cshtml")
@await Html.PartialAsync("~/Views/Shared/Components/_ContactComponentPartial/Default.cshtml")
@await Html.PartialAsync("~/Views/Shared/Components/_FooterComponentPartial/Default.cshtml")

Views/Layout/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - süleyman </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyPortfolioUdemy.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyPortfolioUdemy</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="Index">Hakkında</a>
                        </li>
                      
                       
                        <!-- Diğer Menü Öğeleri -->
                    </ul>
                </div>
            </div>
        </nav>

    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Süleyman  - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/Components/_AboutComponentPartial/Default.cshtml
@model List<süleyman.DAL.Entities.About>

<section id="about" class="s-about target-section">

    <div class="row narrow section-intro has-bottom-sep">
        <div class="col-full text-center">
            <h3>Hakkımda</h3>
            <h2>Ben Süleyman Değirmenci, İstanbul ve Alanya'da dövme sanatçısıyım. Kişiye özel tasarımlar yaparak, her müşterimin kendine özgü hikayesini dövmeye dönüştürüyorum. Sanatımda detaylara ve kaliteye önem veriyorum. Müşterilerimle iyi bir iletişim kurarak, onların isteklerine uygun dövmeler oluşturmayı hedefliyorum. İşim, benim için bir tutku ve her dövme, beni daha da geliştiriyor. Sanat eserlerime aşağıda ulaşabilirsiniz.</h2>
          
        </div>
    </div>

    


     <!-- end about-content timeline -->

</section>

Views/Shared/Components/_FeatureComponentPartial/Default.cshtml
<section id="home" class="s-home page-hero target-section" data-parallax="scroll" data-image-src="/images/sulo10.jpeg" data-natural-width="3000" data-natural-height="2000" data-position-y="center">
    <div class="overlay"></div>
    <div class="shadow-overlay"></div>

    <div class="home-content">
        <div class="row home-content__main">
            <h3>Merhaba</h3>
            <h1>
                Ben Süleyman DEGIRMENCI<br />
                Dövme ve Tasarım için ulaşabilirsiniz.
            </h1>

            <div class="home-content__buttons">
                <a href="#works" class="smoothscroll btn btn--stroke">
                    Son Projelerim
                </a>
                <a href="#about" class="smoothscroll btn btn--stroke">
                    Hakkımda
                </a>
            </div>

            <div class="home-content__scroll">
                <a href="#about" class="scroll-link smoothscroll">
                    <span>Aşağı in</span>
                </a>
            </div>
        </div>
    </div>

    <!-- Sosyal Medya İkonları -->
    <ul class="home-social">
        <li>
            <a href="https://www.instagram.com/olddra/">
                <i class="im im-instagram" aria-hidden="true"></i>
                <span>İnstagram</span>
            </a>
        </li>
        <li>
            <a href="https://wa.me/905534310982" target="_blank">
                <i class="im im-whatsapp" aria-hidden="true"></i>
                <span>WhatsApp</span>
            </a>
        </li>

       
    </ul>
    <!-- end home-social -->

</section>

Views/Shared/Components/_FooterComponentPartial/Default.cshtml
<footer>
    <div class="row">
        <div class="col-full">
            <ul class="footer-social"> 
                <li>
                    <a href="https://www.instagram.com/soulinkk/">
                        <i class="im im-instagram" aria-hidden="true"></i>
                        <span>İnstagram</span>
                    </a>
                </li>
                <li>
                    <a href="https://wa.me/905534310982" target="_blank">
                        <i class="im im-whatsapp" aria-hidden="true"></i>
                        <span>WhatsApp</span>
                    </a>
                </li>
            </ul>

        </div>
    </div>
    <div class="row footer-bottom">
        <div class="col-twelve">
            <div class="copyright">
                <span style="color: #f0f0f0;">© Copyright </span>
                <span style="color: #ffcc00;">
                    <a href="mailto:alirifatciftci@gmail.com" style="color: inherit; text-decoration: none;">
                        Ali Rıfat ÇİFTÇİ
                    </a>
                </span>
                <span style="color: #f0f0f0;"> @DateTime.Now.Year </span>
                <span style="color: #ffcc00;">
                    <a href="mailto:alirifatciftci@gmail.com" style="color: inherit; text-decoration: none;">
                        Design by Ali Rıfat ÇİFTÇİ
                    </a>
                </span>
                <span style="color: #f0f0f0;">
                    <a href="https://www.styleshout.com/" style="color: inherit; text-decoration: none;">Asp.Net Core</a>
                </span>
            </div>

            <div class="go-top">
                <a class="smoothscroll" title="Yukarı Çık" href="#top">
                    <i class="im im-arrow-up" aria-hidden="true"></i>
                </a>
            </div>
        </div>
    </div> <!-- end footer-bottom -->
</footer> <!-- end footer -->
<!-- photoswipe background
================================================== -->
<div aria-hidden="true" class="pswp" role="dialog" tabindex="-1">

    <div class="pswp__bg"></div>
    <div class="pswp__scroll-wrap">

        <div class="pswp__container">
            <div class="pswp__item"></div>
            <div class="pswp__item"></div>
            <div class="pswp__item"></div>
        </div>
        <div class="pswp__ui pswp__ui--hidden">
            <div class="pswp__top-bar">
                <div class="pswp__counter"></div><button class="pswp__button pswp__button--close" title="Close (Esc)"></button> <button class="pswp__button pswp__button--share" title="Share"></button> <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button> <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
                <div class="pswp__preloader">
                    <div class="pswp__preloader__icn">
                        <div class="pswp__preloader__cut">
                            <div class="pswp__preloader__donut"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                <div class="pswp__share-tooltip"></div>
            </div><button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></button> <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)"></button>
            <div class="pswp__caption">
                <div class="pswp__caption__center"></div>
            </div>
        </div>

    </div>

</div><!-- end photoSwipe background -->

<div id="preloader">
    <div id="loader"></div>
</div>


<!-- Java Script
================================================== -->
<script src="~/hola-master/js/jquery-3.2.1.min.js"></script>
<script src="~/hola-master/js/plugins.js"></script>
<script src="~/hola-master/js/main.js"></script>

Views/Shared/Components/_HeadComponentPartial/Default.cshtml
<head>

    <!--- basic page needs
        ================================================== -->
    <header class="s-header">

        <div class="header-logo">
            <a class="smoothscroll" href="#home"><i class="fas fa-home"></i></a>

        </div>

        <nav class="header-nav-wrap">
            <ul class="header-nav">
                <li class="current"><a class="smoothscroll" href="#home" title="home">Anasayfa</a></li>
                <li><a class="smoothscroll" href="#about" title="about">Hakkımda</a></li>
                <li><a class="smoothscroll" href="#works" title="works">Projelerim</a></li>
                <li><a class="smoothscroll" href="#contact" title="contact">İletişim</a></li>
            </ul>
        </nav>

        <a class="header-menu-toggle" href="#0"><span>Menu</span></a>

    </header>
    <meta charset="utf-8">
    <title>Süleyman Değirmenci</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="~/hola-master/css/base.css">
    <link rel="stylesheet" href="~/hola-master/css/vendor.css">
    <link rel="stylesheet" href="~/hola-master/css/main.css">

    <!-- script
    ================================================== -->
    <script src="~/hola-master/js/modernizr.js"></script>
    <script src="~/hola-master/js/pace.min.js"></script>

    <!-- favicons
    ================================================== -->
    <link rel="shortcut icon" href="~/hola-master/favicon.ico" type="image/x-icon">
    <link rel="icon" href="~/hola-master/favicon.ico" type="image/x-icon">

</head>

Views/Shared/Components/_NavbarComponentPartial/Default.cshtml
@{
    Layout = null; 
}

<!DOCTYPE html>
<html lang="en">
<head>
    

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/hola-master/css/base.css" />
    <link rel="stylesheet" href="~/hola-master/css/fonts.css" />
    <link rel="stylesheet" href="~/hola-master/css/main.css" />
    <link rel="stylesheet" href="~/hola-master/css/vendor.css" />
</head>
<body>
  

    <script src="~/hola-master/js/jquery-3.2.1.min.js"></script>
    <script src="~/hola-master/js/main.js"></script>
    <script src="~/hola-master/js/modernizr.js"></script>
    <script src="~/hola-master/js/pace.min.js"></script>
    <script src="~/hola-master/js/plugins.js"></script>
</body>
</html>

Views/Shared/Components/_PortfolioComponentPartial/Default.cshtml
<section id="works" class="s-works target-section">

    <div class="row narrow section-intro has-bottom-sep">
        <div class="col-full">
            <h3>Portfolyo</h3>
            <h1>Son Projelerime Göz Atabilirsiniz.</h1>

            <p class="lead">Aşağıda, dövme projelerimden örnekler yer almaktadır. Her bir çalışma, çeşitli tarzlarda ve tekniklerde yapılmış olup, farklı müşteriler için özelleştirilmiştir. Sanat ve estetik açıdan dikkatle tasarlanmış bu dövmeler, dövme yapımındaki profesyonel yaklaşımımı ve titizliğimi yansıtmaktadır.</p>
        </div>
    </div>

    <div class="row masonry-wrap">
        <div class="masonry">

            <div class="masonry__brick">
                <div class="item-folio">

                    <div class="item-folio__thumb">
                        <a href="/images/buda.jpeg" class="thumb-link" title="Buda" data-size="750x850">
                            <img src="~/images/buda.jpeg" img/>
                                
                            <span class="shadow-overlay"></span>
                        </a>
                    </div>

                    <div class="item-folio__text">
                        <h3 class="item-folio__title">
                            Buda
                        </h3>
                        <p class="item-folio__cat">
                            Colorfull
                        </p>
                    </div>

                  

                    <div class="item-folio__caption">
                        <p>Vero molestiae sed aut natus excepturi. Et tempora numquam. Temporibus iusto quo.Unde dolorem corrupti neque nisi.</p>
                    </div>

                </div> <!-- end item-folio -->
            </div> <!-- end masonry__brick -->

            <div class="masonry__brick">
                <div class="item-folio">

                    <div class="item-folio__thumb">
                        <a href="/images/dali.jpeg" class="thumb-link" title="Salvador Dali" data-size="828x828">
                            <img src="/images/dali.jpeg" img/>
                                
                            <span class="shadow-overlay"></span>
                        </a>
                    </div>

                    <div class="item-folio__text">
                        <h3 class="item-folio__title">
                            Salvador Dali
                        </h3>
                        <p class="item-folio__cat">
                             Design
                        </p>
                    </div>
                   
                    <div class="item-folio__caption">
                        <p>Vero molestiae sed aut natus excepturi. Et tempora numquam. Temporibus iusto quo.Unde dolorem corrupti neque nisi.</p>
                    </div>

                </div> <!-- end item-folio -->
            </div> <!-- end masonry__brick -->

            <div class="masonry__brick">
                <div class="item-folio">

                    <div class="item-folio__thumb">
                        <a href="/images/leon.jpeg" class="thumb-link" data-size="825x825">
                            <img src="/images/leon.jpeg" img/>
                                 
                            <span class="shadow-overlay"></span>
                        </a>
                    </div>

                    <div class="item-folio__text">
                        <h3 class="item-folio__title">
                            The Leon
                        </h3>
                        <p class="item-folio__cat">
                            Design
                    </div>

                  

                    <span class="item-folio__caption">
                        <p>Vero molestiae sed aut natus excepturi. Et tempora numquam. Temporibus iusto quo.Unde dolorem corrupti neque nisi.</p>
                    </span>

                </div> <!-- end item-folio -->
            </div> <!-- end masonry__brick -->


            <div class="masonry__brick">
                <div class="item-folio">

                    <div class="item-folio__thumb">
                        <a href="/images/theeye.jpeg" class="thumb-link" data-size="830x930">
                            <img src="/images/theeye.jpeg" img />
                         
                            <span class="shadow-overlay"></span>
                        </a>
                    </div>

                    <div class="item-folio__text">
                        <h3 class="item-folio__title">
                            The Eye
                        </h3>
                        <p class="item-folio__cat">
                            Design
                        </p>
                    </div>

                

                    <span class="item-folio__caption">
                        <p>Vero molestiae sed aut natus excepturi. Et tempora numquam. Temporibus iusto quo.Unde dolorem corrupti neque nisi.</p>
                    </span>

                </div> <!-- end item-folio -->
            </div> <!-- end masonry__brick -->

            <div class="masonry__brick">
                <div class="item-folio">

                    <div class="item-folio__thumb">
                        <a href="/images/dikeys.jpeg" class="thumb-link" data-size="850x1000">
                            <img src="/images/dikeys.jpeg" img />
              
                            <span class="shadow-overlay"></span>
                        </a>
                    </div>

                    <div class="item-folio__text">
                        <h3 class="item-folio__title">
                            Artist
                        </h3>
                        <p class="item-folio__cat">
                            Süleyman Değirmenci
                        </p>
                    </div>

                   

                    <span class="item-folio__caption">
                        <p>Vero molestiae sed aut natus excepturi. Et tempora numquam. Temporibus iusto quo.Unde dolorem corrupti neque nisi.</p>
                    </span>

                </div> <!-- end item-folio -->
            </div> <!-- end masonry__brick -->

            <div class="masonry__brick">
                <div class="item-folio">

                    <div class="item-folio__thumb">
                        <a href="/images/elephant.jpeg" class="thumb-link" data-size="3000x4000">
                            <img src="/images/elephant.jpeg" img />
                        
                            <span class="shadow-overlay"></span>
                        </a>
                    </div>

                    <div class="item-folio__text">
                        <h3 class="item-folio__title">
                            Elephant
                        </h3>
                        <p class="item-folio__cat">
                            Design
                        </p>
                    </div>

                    
                    <span class="item-folio__caption">
                        <p>Vero molestiae sed aut natus excepturi. Et tempora numquam. Temporibus iusto quo.Unde dolorem corrupti neque nisi.</p>
                    </span>

                </div> <!-- end item-folio -->
            </div> <!-- end masonry__brick -->

            <div class="masonry__brick">
                <div class="item-folio">

                    <div class="item-folio__thumb">
                        <a href="/images/Harry.jpeg" class="thumb-link" data-size="3000x4000">
                            <img src="/images/Harry.jpeg" img />
                                
                            <span class="shadow-overlay"></span>
                        </a>
                    </div>

                    <div class="item-folio__text">
                        <h3 class="item-folio__title">
                            Harry Potter
                        </h3>
                        <p class="item-folio__cat">
                            The Chosen one 
                        </p>
                    </div>

                  
                    <span class="item-folio__caption">
                        <p>Vero molestiae sed aut natus excepturi. Et tempora numquam. Temporibus iusto quo.Unde dolorem corrupti neque nisi.</p>
                    </span>

                </div> <!-- end item-folio -->
            </div> <!-- end masonry__brick -->

            <div class="masonry__brick">
                <div class="item-folio">

                    <div class="item-folio__thumb">
                        <a href="/images/nasus.jpeg" class="thumb-link" data-size="3000x4000">
                            <img src="/images/nasus.jpeg" img />

                            <span class="shadow-overlay"></span>
                        </a>
                    </div>

                    <div class="item-folio__text">
                        <h3 class="item-folio__title">
                            Lord
                        </h3>
                        <p class="item-folio__cat">
                            Design
                        </p>
                    </div>

                    

                    <span class="item-folio__caption">
                        <p>Vero molestiae sed aut natus excepturi. Et tempora numquam. Temporibus iusto quo.Unde dolorem corrupti neque nisi.</p>
                    </span>

                </div> <!-- end item-folio -->
            </div> <!-- end masonry__brick -->
            <div class="masonry__brick">
                <div class="item-folio">

                    <div class="item-folio__thumb">
                        <a href="/images/sulo1.jpeg" class="thumb-link" data-size="960x1280">
                            <img src="/images/sulo1.jpeg" img />

                            <span class="shadow-overlay"></span>
                        </a>
                    </div>

                    <div class="item-folio__text">
                        <h3 class="item-folio__title">
                            Artist  
                        </h3>
                        <p class="item-folio__cat">
                            Süleyman Değirmenci
                        </p>
                    </div>



                    <span class="item-folio__caption">
                        <p>Vero molestiae sed aut natus excepturi. Et tempora numquam. Temporibus iusto quo.Unde dolorem corrupti neque nisi.</p>
                    </span>
                </div> <!-- end item-folio -->
            </div> <!-- end masonry__brick -->

            <div class="masonry__brick">
                <div class="item-folio">

                    <div class="item-folio__thumb">
                        <a href="/images/sulo2.jpeg" class="thumb-link" data-size="960x1280">
                            <img src="/images/sulo2.jpeg" img />

                            <span class="shadow-overlay"></span>
                        </a>
                    </div>

                    <div class="item-folio__text">
                        <h3 class="item-folio__title">
                            Artist
                        </h3>
                        <p class="item-folio__cat">
                            Süleyman Değirmenci
                        </p>
                    </div>



                    <span class="item-folio__caption">
                        <p>Vero molestiae sed aut natus excepturi. Et tempora numquam. Temporibus iusto quo.Unde dolorem corrupti neque nisi.</p>
                    </span>
                </div> <!-- end item-folio -->
            </div> <!-- end masonry__brick -->

            <div class="masonry__brick">
                <div class="item-folio">

                    <div class="item-folio__thumb">
                        <a href="/images/thor.jpeg" class="thumb-link" data-size="4000x5000">
                            <img src="/images/thor.jpeg" img />

                            <span class="shadow-overlay"></span>
                        </a>
                    </div>

                    <div class="item-folio__text">
                        <h3 class="item-folio__title">
                            Thor
                        </h3>
                        <p class="item-folio__cat">
                            Design
                        </p>
                    </div>



                    <span class="item-folio__caption">
                        <p>Vero molestiae sed aut natus excepturi. Et tempora numquam. Temporibus iusto quo.Unde dolorem corrupti neque nisi.</p>
                    </span>
                </div> <!-- end item-folio -->
            </div> <!-- end masonry__brick -->
            <div class="masonry__brick">
                <div class="item-folio">

                    <div class="item-folio__thumb">
                        <a href="/images/zumru.jpeg" class="thumb-link" data-size="3000x4000">
                            <img src="/images/zumru.jpeg" img />

                            <span class="shadow-overlay"></span>
                        </a>
                    </div>

                    <div class="item-folio__text">
                        <h3 class="item-folio__title">
                            Anka

                        </h3>
                        <p class="item-folio__cat">
                            Design
                        </p>
                    </div>



                    <span class="item-folio__caption">
                        <p>Vero molestiae sed aut natus excepturi. Et tempora numquam. Temporibus iusto quo.Unde dolorem corrupti neque nisi.</p>
                    </span>
                </div> <!-- end item-folio -->
            </div> <!-- end masonry__brick -->


        </div>
    </div> <!-- end masonry -->

</section>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - süleyman</title>

    <!-- CSS Dosyaları -->
    <link rel="stylesheet" href="~/hola-master/css/base.css" />
    <link rel="stylesheet" href="~/hola-master/css/fonts.css" />
    <link rel="stylesheet" href="~/hola-master/css/main.css" />
    <link rel="stylesheet" href="~/hola-master/css/vendor.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
  

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Ali Rıfat ÇİFTÇİ - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- JS Dosyaları -->
    <script src="~/hola-master/js/jquery-3.2.1.min.js"></script>
    <script src="~/hola-master/js/main.js"></script>
    <script src="~/hola-master/js/modernizr.js"></script>
    <script src="~/hola-master/js/pace.min.js"></script>
    <script src="~/hola-master/js/plugins.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>